---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
